title: Meu Site Profissional
description: Portfólio e serviços
baseurl: "" # se for site raiz, senão "/nomedirepositorio"
url: "https://welkerzigante.github.io"

theme: minima # ou deixe em branco se for usar layout próprio

plugins:
  - jekyll-feed
  - jekyll-seo-tag
